{
	'pdf_serif_family' : u'Liberation Serif',
	'pdf_header_template' : None,
	'pdf_sans_family' : u'Liberation Sans',
	'pdf_add_toc' : False,
	'pdf_standard_font' : u'serif',
	'pdf_page_numbers' : False,
	'custom_size' : u'7x11',
	'pdf_mono_font_size' : 8,
	'pdf_default_font_size' : 8,
	'pdf_footer_template' : None,
	'override_profile_size' : True,
	'paper_size' : u'letter',
	'preserve_cover_aspect_ratio' : False,
	'toc_title' : None,
	'pdf_mono_family' : u'Liberation Mono',
	'unit' : u'inch',
}